export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_INIT_BALANCE = 'SET_INIT_BALANCE';
export const GOT_PORTFOLIO = 'GOT_PORTFOLIO';
export const GOT_TRANSACTIONS = 'GOT_TRANSACTIONS';
