export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_INIT_BALANCE = 'SET_INIT_BALANCE';
export const GOT_PORTFOLIO = 'GOT_PORTFOLIO';
export const GOT_TRANSACTIONS = 'GOT_TRANSACTIONS';
export const PUBLIC_TOKEN = 'pk_35f24fb074f14600b9e903b545efbef3';
export const HANDLE_STOCK_DATA = 'HANDLE_STOCK_DATA';
export const SET_AUTOCOMPLETE_STOCKS = 'SET_AUTOCOMPLETE_STOCKS';
export const SET_STOCK_PRICE = 'SET_STOCK_PRICE';
